apiVersion: v1
kind: Secret
metadata:
  name: registry-creds-ecr
  namespace: kube-system
  labels:
    app: registry-creds
    kubernetes.io/minikube-addons: registry-creds
    cloud: ecr
data:
  AWS_ACCESS_KEY_ID: {{ required "The AWS accessKey value is required" .Values.ecr.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required "The AWS accessSecret value is required" .Values.ecr.accessSecretKey | b64enc }}
  AWS_SESSION_TOKEN: ""
  aws-account: {{ required "The AWS account is required" .Values.ecr.account | b64enc }}
  aws-region: {{ required "The AWS region is required" .Values.ecr.region | b64enc }}
  aws-assume-role: Y2hhbmdlbWU=
type: Opaque
