apiVersion: v1
kind: Secret
metadata:
  name: maria-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD:  {{ .Values.rootPassword | b64enc }}
  MYSQL_DATABASE: {{ .Values.databaseName | b64enc }}
  MYSQL_USER: {{ .Values.databaseUser | b64enc }}
  MYSQL_PASSWORD: {{ .Values.databasePassword | b64enc }}
