# global configs
email: alandavidg13@gmail.com

# configs for nginx-ingress controller
# nginx-ingress:
#   controller:
#     hostNetwork: true
#     service:
#       type: ClusterIP
#   dnsPolicy: ClusterFirstWithHostNet

# configs for cert-manager
cert-manager:
  startupapicheck:
    timeout: 5m
  crds:
    enabled: true
