apiVersion: apps/v1
kind: Deployment
metadata:
  name: komga-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komga-deploy
  template:
    metadata:
      labels:
        app: komga-deploy
    spec:
      containers:
        - name: komga
          image: gotson/komga
          ports:
            - containerPort: 25600
          volumeMounts:
            - name: komga-data
              mountPath: /config
            - name: komga-data
              mountPath: /data
      volumes:
        - name: komga-data
          persistentVolumeClaim:
            claimName: komga-pvc
