apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: komga-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.domainName }}
    secretName: letsencrypt-prod
  rules:
  - host: {{ .Values.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: komga-svc
            port:
              number: 25600
