apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-data
  namespace: default
  labels:
    app: komga-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
